services:
  - type: worker
    name: telegram-gemini-bot
    env: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p logs
    startCommand: bash start.sh
    plan: free
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
      - key: TELEGRAM_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
