services:
  - type: worker
    name: telegram-gemini-bot
    env: python
    buildCommand: |
      pip install -r requirements.txt
      chmod +x start.sh
    startCommand: bash start.sh
    plan: free
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
