services:
  - type: web
    name: telegram-gemini-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python telegram_gemini_bot_amirrezatube.py
    envVars:
      - key: TELEGRAM_TOKEN
        value: your_telegram_token_here
      - key: GEMINI_API_KEY
        value: your_gemini_api_key_here
