services:
  - type: web
    name: telegram-gemini-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn telegram_gemini_bot_amirrezatube:app
    healthCheckPath: /health
    autoDeploy: true
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: 1
